[versions]
kotlin = "1.9.0"
agp = "8.2.2"
compose-bom = "2023.08.00"
room = "2.6.1"
lifecycle = "2.7.0"
activity-compose = "1.8.2"
navigation = "2.7.7"
datastore = "1.0.0"
material3 = "1.2.0"
coil = "2.5.0"
gson = "2.10.1"

[libraries]
core-ktx = "androidx.core:core-ktx:1.12.0"
lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:{lifecycle}"
activity-compose = "androidx.activity:activity-compose:{activity-compose}"
navigation-compose = "androidx.navigation:navigation-compose:{navigation}"
datastore-preferences = "androidx.datastore:datastore-preferences:{datastore}"
room-runtime = "androidx.room:room-runtime:{room}"
room-ktx = "androidx.room:room-ktx:{room}"
room-compiler = "androidx.room:room-compiler:{room}"
gson = "com.google.code.gson:gson:{gson}"
coil-compose = "io.coil-kt:coil-compose:{coil}"

[bundles]
compose = [
  "androidx.compose.ui:ui",
  "androidx.compose.ui:ui-graphics",
  "androidx.compose.ui:ui-tooling-preview",
  "androidx.compose.material3:material3"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
